# Generated by Django 3.0.8 on 2020-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='pics')),
                ('password', models.CharField(max_length=40)),
                ('eno', models.CharField(max_length=13)),
            ],
        ),
    ]
